### ISSUE TITLE
Fix line ending in Additional Info

### ISSUE THREAD

**Issue by katemorkeski** [WHOIGit/nes-lter-npp-transect#12]
Kate still has one turning up

**Comment by joannekoch** [comment]
@katemorkeski, additional_info.txt has not been updated in github since Dec 2022. When you commit a new version to the main repo, the line endings will be changed from CR LF to unix LF. Is this what you are referring to?

**Comment by joannekoch** [comment]
This issue is referring to 2 lines in the github committed file, knb-lter-nes.16.4.xml, which contain `&#13`. This is an escaped non-printing carriage return which is not removed with .gitattributes.

Since there are just 2 occurances in the file and only 2 diffs because of it, I recommend we ignore it and do not attempt to implement a fix to strip it out of the files we commit.

@katemorkeski , if you agree please close this issue
